import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { Icons } from "@/components/ui/icons";
import { TrafficChart } from "@/components/ga4/traffic-chart";
import { assignGa4Property, syncGa4Performance } from "./actions";

export default async function AnalyticsPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ga4?:string}>}) {
  const {id}=await params; const query=await searchParams; const supabase=await createClient();
  const {data:client}=await supabase.from("clients").select("*").eq("id",id).single(); if(!client) notFound();
  const {data:linked}=await supabase.from("ga4_properties").select("*").eq("client_id",id).maybeSingle();
  const {data:available}=await supabase.from("ga4_properties").select("id,property_id,display_name").eq("organisation_id",client.organisation_id).order("display_name");
  const {data:metrics}=await supabase.from("ga4_daily_metrics").select("metric_date,active_users,sessions,engaged_sessions,key_events,total_revenue").eq("client_id",id).order("metric_date").limit(90);
  const rows=(metrics??[]).map((r:any)=>({...r,active_users:Number(r.active_users),sessions:Number(r.sessions),engaged_sessions:Number(r.engaged_sessions),key_events:Number(r.key_events),total_revenue:Number(r.total_revenue)}));
  const current=rows.slice(-28); const sum=(k:string)=>current.reduce((a:any,r:any)=>a+r[k],0); const sessions=sum("sessions"), users=sum("active_users"), engaged=sum("engaged_sessions"), events=sum("key_events"), revenue=sum("total_revenue");
  const messages:Record<string,string>={"property-linked":"GA4 property linked.","sync-complete":"GA4 data synced.","sync-failed":"GA4 sync failed. Check the latest sync details.","no-linked-property":"Choose a GA4 property first.","assign-failed":"The GA4 property could not be linked."};
  return <><Link href={`/dashboard/clients/${id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-[#181818]"><span className="rotate-180"><Icons.arrow className="h-4 w-4"/></span>Back to {client.name}</Link>
  <div className="mt-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-bold text-[#181818]">Google Analytics 4</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#181818] sm:text-4xl">Organic traffic & conversions</h1><p className="mt-2 text-slate-500">Connect search visibility to website engagement and outcomes.</p></div><div className="flex gap-3">{linked?<form action={syncGa4Performance.bind(null,id)}><button className="btn-primary" type="submit">Sync GA4 data</button></form>:null}<a href={`/api/google/connect?clientId=${id}`} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-800">Reconnect Google</a></div></div>
  {query.ga4&&messages[query.ga4]?<div className="mt-6 rounded-2xl border border-lime-200 bg-lime-50 px-4 py-3 text-sm font-semibold">{messages[query.ga4]}</div>:null}
  <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Organic sessions",sessions.toLocaleString()],["Active users",users.toLocaleString()],["Engagement rate",sessions?`${((engaged/sessions)*100).toFixed(1)}%`:"—"],["Key events",events.toLocaleString()],["Revenue",`£${revenue.toLocaleString(undefined,{maximumFractionDigits:0})}`]].map(([l,v])=><article key={l} className="app-card p-5"><p className="text-sm font-semibold text-slate-500">{l}</p><p className="mt-3 text-3xl font-bold text-[#181818]">{rows.length?v:"—"}</p><p className="mt-2 text-xs text-slate-400">Last 28 days</p></article>)}</section>
  <section className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><article className="app-card p-6 sm:p-7"><h2 className="font-bold text-slate-900">Organic traffic trend</h2><p className="mt-1 mb-8 text-sm text-slate-500">Sessions and active users from Organic Search.</p><TrafficChart data={rows.map((r:any)=>({date:r.metric_date,sessions:r.sessions,users:r.active_users}))}/></article><article className="app-card p-6"><h2 className="font-bold text-slate-900">GA4 property</h2><p className="mt-1 text-sm text-slate-500">Choose the Analytics property for this client.</p>{available?.length?<form action={assignGa4Property.bind(null,id)} className="mt-5 space-y-3"><select name="propertyId" defaultValue={linked?.id??""} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="" disabled>Choose a property</option>{available.map((p:any)=><option key={p.id} value={p.id}>{p.display_name} ({p.property_id})</option>)}</select><button className="btn-primary w-full justify-center" type="submit">Link GA4 property</button></form>:<div className="mt-5 rounded-xl bg-lime-50 p-4 text-sm">Reconnect Google to grant Analytics read-only access and retrieve properties.</div>}{linked?<dl className="mt-6 space-y-3 text-sm"><div><dt className="text-slate-400">Connected property</dt><dd className="mt-1 font-bold">{linked.display_name}</dd></div><div><dt className="text-slate-400">Last sync</dt><dd className="mt-1 font-bold">{linked.last_synced_at?new Date(linked.last_synced_at).toLocaleString("en-GB"):"Never"}</dd></div></dl>:null}</article></section></>;
}
