import Link from "next/link";
import { notFound } from "next/navigation";
import { PrintReportButton } from "@/components/reports/report-view";
import { ReportDocument } from "@/components/reports/report-document";
import { createClient } from "@/lib/supabase/server";
import { updateReport } from "../actions";

export default async function ReportPage({ params }: { params: Promise<{ reportId: string }> }) {
  const { reportId } = await params; const supabase = await createClient();
  const { data: report } = await supabase.from("client_reports").select("*, clients(name, domain)").eq("id", reportId).single();
  if (!report) notFound(); const client = Array.isArray(report.clients) ? report.clients[0] : report.clients;
  const { data: currentRows } = await supabase.from("gsc_daily_metrics").select("metric_date, clicks, impressions, position").eq("client_id", report.client_id).gte("metric_date", report.date_from).lte("metric_date", report.date_to).order("metric_date");
  const { data: previousRows } = await supabase.from("gsc_daily_metrics").select("metric_date, clicks, impressions, position").eq("client_id", report.client_id).gte("metric_date", report.comparison_date_from).lte("metric_date", report.comparison_date_to).order("metric_date");
  const { data: currentGa4Rows } = await supabase.from("ga4_daily_metrics").select("metric_date, sessions, active_users, engaged_sessions, key_events, total_revenue").eq("client_id", report.client_id).gte("metric_date", report.date_from).lte("metric_date", report.date_to).order("metric_date");
  const { data: previousGa4Rows } = await supabase.from("ga4_daily_metrics").select("metric_date, sessions, active_users, engaged_sessions, key_events, total_revenue").eq("client_id", report.client_id).gte("metric_date", report.comparison_date_from).lte("metric_date", report.comparison_date_to).order("metric_date");
  const { data: dimensions } = await supabase.from("gsc_dimension_metrics").select("dimension_type, dimension_value, clicks, impressions, ctr, position").eq("client_id", report.client_id).eq("period_key", "current").order("clicks", { ascending: false }).limit(40);
  const top = (type: string) => (dimensions ?? []).filter((row) => row.dimension_type === type).slice(0, 10).map((row) => ({ ...row, clicks: Number(row.clicks), impressions: Number(row.impressions), ctr: Number(row.ctr), position: Number(row.position) }));
  return <div><div className="no-print mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><Link href="/dashboard/reports" className="text-sm font-bold text-slate-500 hover:text-black">← All reports</Link><h1 className="mt-2 text-2xl font-bold text-slate-900">Report editor</h1></div><div className="flex flex-wrap gap-3"><PrintReportButton />{report.status === "published" ? <Link href={`/reports/${report.public_token}`} target="_blank" className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold">Open public report</Link> : null}</div></div>
    <form action={updateReport.bind(null, reportId)} className="no-print app-card mb-8 grid gap-5 p-6 lg:grid-cols-3"><label className="lg:col-span-3"><span className="text-sm font-bold">Title</span><input name="title" defaultValue={report.title} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label><span className="text-sm font-bold">Executive summary</span><textarea name="executive_summary" defaultValue={report.executive_summary} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label><span className="text-sm font-bold">Work completed</span><textarea name="work_completed" defaultValue={report.work_completed} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label><span className="text-sm font-bold">Next steps</span><textarea name="next_steps" defaultValue={report.next_steps} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><div className="lg:col-span-3 flex flex-wrap gap-3"><button name="status" value="draft" className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold">Save draft</button><button name="status" value="published" className="btn-primary">Publish report</button></div></form>
    <ReportDocument report={report} client={client} currentRows={(currentRows ?? []).map((r) => ({ ...r, clicks: Number(r.clicks), impressions: Number(r.impressions), position: Number(r.position) }))} previousRows={(previousRows ?? []).map((r) => ({ ...r, clicks: Number(r.clicks), impressions: Number(r.impressions), position: Number(r.position) }))} currentGa4Rows={(currentGa4Rows ?? []).map((r) => ({ ...r, sessions: Number(r.sessions), active_users: Number(r.active_users), engaged_sessions: Number(r.engaged_sessions), key_events: Number(r.key_events), total_revenue: Number(r.total_revenue) }))} previousGa4Rows={(previousGa4Rows ?? []).map((r) => ({ ...r, sessions: Number(r.sessions), active_users: Number(r.active_users), engaged_sessions: Number(r.engaged_sessions), key_events: Number(r.key_events), total_revenue: Number(r.total_revenue) }))} topQueries={top("query")} topPages={top("page")} />
  </div>;
}
